version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express_app
    volumes:
      - /usr/src/node_modules
      - .:/usr/src/app
    command: yarn dev
    ports:
      - "3001:3001"